stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/data.csv

  data_transformation:
    cmd: python src/components/data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/proprocessor.pkl

  model_training:
    cmd: python src/components/model_trainer.py
    deps:
      - src/components/model_trainer.py
      - artifacts/proprocessor.pkl
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/model.pkl
